apiVersion: apps/v1
kind: Deployment
metadata:
    name: simple-nginx
spec:
    selector:
        matchLabels:
            app: simple-nginx
    replicas: 1
    template:
        metadata:
            labels:
                app: simple-nginx
        spec:
            containers:
                - name: simple-nginx-front-end
                  image: ${DOCKER_REGISTRY_HOSTNAME}/${DOCKER_IMAGE_NAMESPACE}/${DOCKER_IMAGE_REPOSITORY}:${DOCKER_IMAGE_TAG}
                  ports:
                      - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
    name: simple-nginx-service
spec:
    selector:
        app: simple-nginx
    ports:
        - port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: simple-nginx-ingress
spec:
    rules:
        - host: ${DOCKER_APPLICATION_FQDN}
          http:
              paths:
                  - backend:
                        serviceName: simple-nginx-service
                        servicePort: 80
